spring.profiles.active=dev

spring.application.name=GezhiPlatform
spring.jackson.time-zone=Asia/Shanghai
server.error.include-path=never
server.error.include-stacktrace=never
spring.mvc.problemdetails.enabled=true
server.port=8080

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Datasource
spring.datasource.hikari.max-lifetime=580000
spring.datasource.hikari.keepalive-time=300000

# JPA
spring.jpa.properties.hibernate.default_batch_fetch_size=32

# Batch insert and update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true